---
# tasks file for rabbitmq
- name: Transfer the script
  copy: src=/home/elush/ansible/rabbitmq/rabbit.inst dest=/home/elush mode=0777

- name: Execute the script
  command: sh /home/elush/rabbit.inst
  become: true  

- rabbitmq_user:
    user: rabbituser
    password: "your password"
    vhost: /
    configure_priv: .*
    read_priv: .*
    write_priv: .*
    state: present  
  become: true
