---
# tasks file for java
- name: 'Update apt repo and cache'
  apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
  become: true
- name: Install latest version of "openjdk-8-jdk" ignoring "install-recommends"
  apt:
    name: openjdk-8-jdk
    state: present
  become: true

- name: 'Install maven'
  apt:
    name: maven
    state: present
  become: true
